import React from 'react'

const Terms = () => {
  return (
    <section className='space-y-10'>
      <div className='space-y-2'>
        <h3 className='font-bold text-3xl lg:text-4xl'>01 Terms</h3>
        <p className='lg:text-lg'>Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.</p>
      </div>
      <div className='space-y-2'>
        <h3 className='font-bold text-3xl lg:text-4xl'>02 Use License</h3>
        <p className='lg:text-lg'>Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.</p>
      </div>
      <div className='space-y-2'>
        <h3 className='font-bold text-3xl lg:text-4xl'>03 Disclaimer</h3>
        <p className='lg:text-lg'>Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.</p>
      </div>
      <div className='space-y-2'>
        <h3 className='font-bold text-3xl lg:text-4xl'>04 Limitations</h3>
        <p className='lg:text-lg'>Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.</p>
      </div>
      <div className='space-y-2'>
        <h3 className='font-bold text-3xl lg:text-4xl'>05 Accuracy of Materials</h3>
        <p className='lg:text-lg'>Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.</p>
      </div>
      <div className='space-y-2'>
        <h3 className='font-bold text-3xl lg:text-4xl'>06 Links</h3>
        <p className='lg:text-lg'>Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.</p>
      </div>
      <div className='space-y-2'>
        <h3 className='font-bold text-3xl lg:text-4xl'>07 Modifications</h3>
        <p className='lg:text-lg'>Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.</p>
      </div>
      <div className='space-y-2'>
        <h3 className='font-bold text-3xl lg:text-4xl'>08 Governing Law</h3>
        <p className='lg:text-lg'>Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.Lorem ipsum dolor sit amet consectetur. Tortor euismod eu aliquam odio congue pellentesque eget. Amet proin vitae massa accumsan et commodo sed. Elementum dui ipsum urna tortor enim. Sollicitudin at egestas viverra a mauris id scelerisque purus cras. Maecenas in massa in purus dui orci. Elementum pretium sapien vulputate odio ipsum commodo. Facilisi sapien malesuada parturient ut phasellus. Ultricies ac viverra molestie at pretium.</p>
      </div>
    </section>
  )
}

export default Terms